"""One-shot generator for metadata.json. Run once; safe to re-run.

Builds the metadata array from a hand-curated list of records describing
each Huggy asset. Display names for Modern + Outlined preserve the curator
filenames; Collection 2026 names are chosen to be searchable.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "metadata.json"


def slugify(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


# ---------- Modern Huggies (29) ----------
MODERN = [
    # filename, display_name, description, expression, pose, hands, headwear, outfit, face_acc, held, effects, colors, mood, theme, tags, synonyms
    ("Acedemic Huggy.png", "Acedemic Huggy",
     "Yellow Huggy wearing a graduation cap, smiling and holding a blue pointer stick.",
     "happy_open_mouth", "default", "pointing",
     ["graduation cap"], [], [], ["pointer"], [],
     ["yellow", "purple", "blue"], ["proud", "smart"], ["education", "academic"],
     ["academic", "graduation", "cap", "school", "teacher", "student", "professor", "education"],
     ["scholar", "diploma"]),
    ("Back of a Huggy.png", "Back of a Huggy",
     "View of Huggy from behind, holding a pink and blue notebook with both hands.",
     "unknown", "back_view", "holding",
     [], [], [], ["notebook"], [],
     ["yellow", "blue", "pink"], ["calm"], ["work"],
     ["back", "behind", "notebook", "rear", "book", "study"],
     ["backside", "rear-view"]),
    ("computer vision Huggy.png", "computer vision Huggy",
     "Yellow Huggy with mouth open, reading a blue book while holding a pencil and emoji cards.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["book", "pencil", "emoji cards"], [],
     ["yellow", "blue", "red"], ["focused", "happy"], ["ml", "computer-vision"],
     ["vision", "computer-vision", "ml", "ai", "book", "study", "labeling", "annotation"],
     ["cv", "labels"]),
    ("D Huggy.png", "D Huggy",
     "Yellow Huggy as a detective with a magnifying glass over one eye, headphones, and a pink eraser.",
     "winking", "default", "holding",
     [], [], ["magnifying glass"], ["magnifying glass", "eraser"], ["question mark"],
     ["yellow", "pink"], ["curious", "investigative"], ["detective"],
     ["detective", "magnifying", "glass", "investigate", "spy", "search", "clue", "curious"],
     ["sherlock", "sleuth"]),
    ("Doodle Huggy.gif", "Doodle Huggy",
     "Hand-drawn doodle style Huggy with messy yellow hair, big smile, and a pink music note.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], [], ["music note"],
     ["yellow", "pink"], ["fun", "playful"], ["doodle", "art"],
     ["doodle", "sketch", "drawing", "messy", "music", "fun", "scribble", "rough"],
     ["doodled", "handdrawn"]),
    ("Dragon Huggy.png", "Dragon Huggy",
     "Yellow Huggy wearing a green dragon-head costume with antlers and pink scales.",
     "happy_open_mouth", "default", "open_palm",
     ["dragon costume"], [], [], [], [],
     ["yellow", "green", "pink"], ["festive", "playful"], ["lunar-new-year", "mythical"],
     ["dragon", "costume", "lunar", "new-year", "mythical", "antlers", "asian", "zodiac"],
     ["chinese-new-year", "wyrm"]),
    ("Game Jam Huggy.png", "Game Jam Huggy",
     "Two yellow Huggies sitting together holding video game controllers, one winking.",
     "winking", "default", "holding",
     [], [], [], ["controller"], ["sparkles"],
     ["yellow"], ["fun", "competitive"], ["gaming"],
     ["game", "gaming", "controller", "jam", "play", "video-game", "console", "two"],
     ["esports", "gamepad"]),
    ("Huggy blink Okay.png", "Huggy blink Okay",
     "Yellow Huggy with one eye winking and an OK hand sign, smiling.",
     "winking", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["happy", "playful"], ["reaction"],
     ["okay", "ok", "wink", "blink", "fine", "approve", "happy"],
     ["alright", "agreed"]),
    ("Huggy Chef.png", "Huggy Chef",
     "Yellow Huggy wearing a tall white chef's hat with sparkles and a small sugar cube on a tray.",
     "starry_eyes", "default", "open_palm",
     ["chef hat"], [], [], ["sugar cube"], ["sparkles", "hearts"],
     ["yellow", "white"], ["passionate", "happy"], ["cooking", "food"],
     ["chef", "cook", "kitchen", "hat", "food", "baking", "cooking", "sweet"],
     ["baker", "cuisine"]),
    ("Huggy Hi.png", "Huggy Hi",
     "Yellow Huggy with a wide smile and both hands raised in a friendly greeting.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow"], ["friendly", "happy"], ["greeting"],
     ["hi", "hello", "hey", "wave", "greeting", "welcome", "friendly"],
     ["howdy", "salute"]),
    ("Huggy Lab.png", "Huggy Lab",
     "Yellow Huggy in a white lab coat holding up a teal test tube.",
     "happy_open_mouth", "default", "holding",
     [], ["lab coat"], [], ["test tube"], [],
     ["yellow", "white", "teal"], ["curious", "scientific"], ["science"],
     ["lab", "scientist", "test-tube", "science", "chemistry", "research", "experiment"],
     ["chemist", "researcher"]),
    ("Huggy Medic.png", "Huggy Medic",
     "Yellow Huggy with a white nurse cap and red cross, holding a black stethoscope.",
     "happy_open_mouth", "default", "holding",
     ["nurse cap"], [], [], ["stethoscope"], [],
     ["yellow", "white", "red"], ["caring", "happy"], ["medical"],
     ["medic", "nurse", "doctor", "stethoscope", "health", "medical", "hospital", "care"],
     ["physician", "healthcare"]),
    ("Huggy Okay.png", "Huggy Okay",
     "Yellow Huggy with closed eyes, big smile, and an OK hand gesture.",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["happy", "calm"], ["reaction"],
     ["okay", "ok", "fine", "smile", "happy", "approve", "satisfied"],
     ["alright", "good"]),
    ("Huggy Pop.gif", "Huggy Pop",
     "Animated pop-style Huggy (animated GIF, frame may appear blank).",
     "unknown", "default", "default",
     [], [], [], [], [],
     ["yellow"], ["fun"], ["animated"],
     ["pop", "animated", "gif", "loop", "motion"],
     ["bounce", "wiggle"]),
    ("Huggy Sunny hello.png", "Huggy Sunny hello",
     "Yellow Huggy peeking from edge with a friendly wave on a blue background.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], ["motion lines"],
     ["yellow", "blue"], ["friendly", "happy"], ["greeting", "banner"],
     ["sunny", "hello", "hi", "wave", "greeting", "friendly", "blue"],
     ["howdy", "welcome"]),
    ("Huggy Sunny.png", "Huggy Sunny",
     "Yellow Huggy partially shown smiling on a blue background, hand raised.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow", "blue"], ["happy", "calm"], ["banner"],
     ["sunny", "wave", "happy", "hello", "blue", "background"],
     ["bright", "cheery"]),
    ("Huggy the Pooh meme.png", "Huggy the Pooh meme",
     "Two-panel meme of Huggy: top panel plain, bottom panel wearing pixel sunglasses and bow tie.",
     "smug", "default", "open_palm",
     [], [], ["pixel sunglasses", "bow tie"], [], [],
     ["yellow", "gray", "black"], ["smug", "cool"], ["meme"],
     ["meme", "pooh", "sunglasses", "tuxedo", "smug", "cool", "fancy", "comparison"],
     ["bear", "drake"]),
    ("Huggy Yolk.png", "Huggy Yolk",
     "Yellow Huggy hatching out of a cracked white egg shell, smiling.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], ["egg shell"], [],
     ["yellow", "white"], ["new", "happy"], ["birth"],
     ["yolk", "egg", "hatch", "born", "new", "shell", "baby", "chick"],
     ["hatching", "newborn"]),
    ("IDEFICS Huggy.png", "IDEFICS Huggy",
     "Yellow Huggy with red braided hair and mustache holding a black-and-white rabbit doll.",
     "peaceful_closed", "default", "holding",
     ["red braids", "mustache"], [], [], ["rabbit doll"], [],
     ["yellow", "red", "white"], ["calm", "quirky"], ["model", "ml"],
     ["idefics", "braids", "rabbit", "doll", "mustache", "pippi", "ml", "model"],
     ["pigtails", "bunny"]),
    ("Karaoke Huggy.png", "Karaoke Huggy",
     "Yellow Huggy with eyes closed singing into a black microphone with a blue music note.",
     "peaceful_closed", "default", "holding",
     [], [], [], ["microphone"], ["music note"],
     ["yellow", "blue", "black"], ["happy", "musical"], ["music"],
     ["karaoke", "sing", "microphone", "music", "song", "mic", "performance"],
     ["singing", "vocal"]),
    ("Lora Huggy.png", "Lora Huggy",
     "Yellow Huggy with a brown bob haircut, surprised expression, and a purple handbag.",
     "happy_open_mouth", "default", "waving",
     ["brown bob"], [], [], ["purse"], ["exclamation"],
     ["yellow", "brown", "purple"], ["surprised", "happy"], ["fashion", "ml"],
     ["lora", "bob", "haircut", "purse", "bag", "fashion", "fine-tune", "adapter"],
     ["finetune", "stylish"]),
    ("Optimum Huggy.png", "Optimum Huggy",
     "Yellow Huggy lifting a barbell with two purple cubes, wearing an Optimum belt.",
     "happy_open_mouth", "default", "holding",
     [], ["weightlifter belt"], [], ["barbell"], [],
     ["yellow", "blue", "purple"], ["strong", "confident"], ["fitness", "performance"],
     ["optimum", "weights", "barbell", "lift", "strong", "fitness", "gym", "performance"],
     ["powerlift", "strength"]),
    ("Robot Huggy.png", "Robot Huggy",
     "Yellow Huggy with sparkling eyes hugging a black camera/robot device with a red heart screen.",
     "starry_eyes", "default", "hugging",
     [], [], [], ["robot camera"], [],
     ["yellow", "black", "red"], ["loving", "excited"], ["robotics"],
     ["robot", "camera", "robotics", "love", "machine", "device", "tech"],
     ["bot", "android"]),
    ("Snake Huggy.png", "Snake Huggy",
     "Yellow Huggy wearing a green snake hat with big white eyes and red tongue.",
     "happy_open_mouth", "default", "open_palm",
     ["snake hat"], [], [], [], [],
     ["yellow", "green", "red"], ["festive", "playful"], ["lunar-new-year", "zodiac"],
     ["snake", "lunar", "zodiac", "year", "costume", "reptile", "asian"],
     ["serpent", "viper"]),
    ("Super Huggy.png", "Super Huggy",
     "Yellow Huggy in dynamic flying pose with confetti streaks, fist raised triumphantly.",
     "happy_open_mouth", "rushing_right", "fist_forward",
     [], [], [], [], ["confetti", "speed lines"],
     ["yellow", "red", "blue", "purple"], ["excited", "powerful"], ["super", "celebration"],
     ["super", "hero", "fly", "confetti", "celebrate", "power", "fist", "energy"],
     ["superhero", "victory"]),
    ("Text Generation Wizard Huggy.png", "Text Generation Wizard Huggy",
     "Yellow Huggy in dark wizard hat holding a wooden staff and glowing diamond crystal, surrounded by floating letters.",
     "happy_open_mouth", "default", "holding",
     ["wizard hat"], [], [], ["staff", "crystal"], ["floating letters"],
     ["yellow", "blue", "purple"], ["magical", "creative"], ["nlp", "magic"],
     ["wizard", "text", "generation", "magic", "nlp", "staff", "spell", "language"],
     ["mage", "sorcerer"]),
    ("Transformer Agent Huggy.png", "Transformer Agent Huggy",
     "Yellow Huggy with binary-code visor sunglasses, holding star-shaped tokens and a star ornament.",
     "cool_smirk", "default", "holding",
     [], [], ["binary visor"], ["star tokens"], [],
     ["yellow", "black", "green"], ["cool", "tech"], ["agents", "ml"],
     ["transformer", "agent", "binary", "code", "ai", "matrix", "visor", "tokens"],
     ["coder", "hacker"]),
    ("Vibing Huggy.gif", "Vibing Huggy",
     "Yellow Huggy with closed eyes and big smile making finger-gun shaka gestures (animated).",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["chill", "happy"], ["vibe", "animated"],
     ["vibing", "vibe", "chill", "shaka", "groove", "happy", "animated", "gif"],
     ["relax", "mood"]),
    ("Wine Huggy.png", "Wine Huggy",
     "Yellow Huggy with closed eyes drinking from a wine glass, shaka hand gesture.",
     "peaceful_closed", "default", "holding",
     [], [], [], ["wine glass"], [],
     ["yellow", "purple"], ["relaxed", "happy"], ["drink", "social"],
     ["wine", "drink", "glass", "alcohol", "relax", "shaka", "happy", "cheers"],
     ["sip", "merlot"]),
]

# ---------- Outlined Huggies (18) ----------
OUTLINED = [
    ("Catching Huggy.png", "Catching Huggy",
     "Outlined Huggy catching a stack of falling colorful books or papers in its arms.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["books"], ["motion lines"],
     ["yellow", "purple", "red", "blue"], ["alert", "happy"], ["work"],
     ["catch", "books", "stack", "fall", "save", "rescue", "papers", "data"],
     ["grab", "snag"]),
    ("Comic Huggy.png", "Comic Huggy",
     "Outlined Huggy with a beret holding an oversized paintbrush dripping red paint and a paint palette.",
     "happy_open_mouth", "default", "holding",
     ["beret"], [], [], ["paintbrush", "palette"], [],
     ["yellow", "blue", "red"], ["creative", "playful"], ["art"],
     ["comic", "art", "paint", "brush", "palette", "artist", "beret", "draw"],
     ["painter", "illustrator"]),
    ("Curious Huggy.png", "Curious Huggy",
     "Outlined Huggy holding a magnifying glass to one eye with a question mark, examining a pink object.",
     "winking", "default", "holding",
     [], [], [], ["magnifying glass"], ["question mark"],
     ["yellow", "pink"], ["curious", "puzzled"], ["search"],
     ["curious", "magnifying", "search", "investigate", "question", "wonder", "examine"],
     ["inquisitive", "explore"]),
    ("Diffusor guide Huggy.png", "Diffusor guide Huggy",
     "Outlined Huggy with a smug grin holding a thermometer-like ruler with a blue diffusion crystal.",
     "smug", "default", "holding",
     [], [], [], ["ruler", "crystal"], [],
     ["yellow", "blue"], ["smug", "knowing"], ["diffusion", "guide"],
     ["diffusion", "diffusor", "guide", "ruler", "crystal", "model", "tutorial"],
     ["diffuser", "howto"]),
    ("Fishing Huggy.png", "Fishing Huggy",
     "Outlined Huggy in green bucket hat fishing with a rod and red bobber in water, music notes nearby.",
     "happy_open_mouth", "default", "holding",
     ["bucket hat"], [], [], ["fishing rod"], ["music note"],
     ["yellow", "green", "red"], ["calm", "happy"], ["leisure"],
     ["fishing", "rod", "fish", "hat", "calm", "leisure", "outdoor", "river"],
     ["angler", "catch"]),
    ("Global Huggy.png", "Global Huggy",
     "Outlined Huggy with starry eyes pointing at a blue globe on a stand.",
     "starry_eyes", "default", "pointing",
     [], [], [], ["globe"], [],
     ["yellow", "blue"], ["excited", "curious"], ["global", "world"],
     ["global", "world", "globe", "earth", "international", "geography", "travel"],
     ["worldwide", "planet"]),
    ("GPU Huggy.png", "GPU Huggy",
     "Outlined Huggy with sparkle eyes hugging a black GPU chip with teal core, smiling.",
     "starry_eyes", "default", "hugging",
     [], [], [], ["GPU chip"], ["motion lines"],
     ["yellow", "black", "teal"], ["excited", "tech"], ["hardware", "compute"],
     ["gpu", "chip", "compute", "hardware", "graphics", "card", "ml", "training"],
     ["graphics", "processor"]),
    ("Greeting Huggy left.png", "Greeting Huggy left",
     "Two outlined Huggies side by side, one with a thumbs up and the other waving.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow"], ["friendly", "happy"], ["greeting"],
     ["greeting", "wave", "hi", "hello", "two", "thumbs-up", "left", "friends"],
     ["welcome", "duo"]),
    ("Greeting Huggy right.png", "Greeting Huggy right",
     "Outlined Huggy facing right with mouth open and one hand waving from behind.",
     "happy_open_mouth", "tilted_right", "waving",
     [], [], [], [], ["motion lines"],
     ["yellow"], ["friendly", "happy"], ["greeting"],
     ["greeting", "wave", "hi", "hello", "right", "smile", "friendly"],
     ["welcome", "salute"]),
    ("Growing model Huggy.png", "Growing model Huggy",
     "Outlined Huggy watering a plant pot growing a blue model crystal with a blue watering can.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["watering can"], ["water drops"],
     ["yellow", "blue", "green"], ["nurturing", "happy"], ["model-training", "growth"],
     ["growing", "model", "watering", "plant", "grow", "training", "nurture", "ml"],
     ["cultivate", "develop"]),
    ("Guide Huggy.png", "Guide Huggy",
     "Outlined Huggy with a smug expression holding a large thermometer-style ruler with a blue crystal.",
     "smug", "default", "holding",
     [], [], [], ["ruler", "crystal"], [],
     ["yellow", "blue"], ["confident", "knowing"], ["guide", "tutorial"],
     ["guide", "ruler", "tutorial", "howto", "thermometer", "crystal", "smug", "expert"],
     ["instruction", "manual"]),
    ("Loving modelndataset Huggy.png", "Loving modelndataset Huggy",
     "Outlined Huggy with closed eyes leaning lovingly against an aquarium of model and dataset cubes.",
     "peaceful_closed", "leaning_right", "open_palm",
     [], [], [], ["aquarium"], ["heart"],
     ["yellow", "purple", "red", "blue"], ["loving", "calm"], ["model", "dataset"],
     ["love", "model", "dataset", "aquarium", "tank", "data", "ml", "fish"],
     ["adore", "datapool"]),
    ("Manager Huggy.png", "Manager Huggy",
     "Outlined Huggy holding an orange clipboard with a checklist, waving with the other hand.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["clipboard"], [],
     ["yellow", "orange"], ["organized", "happy"], ["work", "management"],
     ["manager", "clipboard", "checklist", "tasks", "todo", "organize", "work", "list"],
     ["pm", "supervisor"]),
    ("Paper Huggy.png", "Paper Huggy",
     "Outlined Huggy with blue backpack holding a rolled-up scroll/paper diploma.",
     "happy_open_mouth", "default", "holding",
     [], ["backpack"], [], ["scroll", "paper"], [],
     ["yellow", "blue"], ["proud", "happy"], ["research", "academic"],
     ["paper", "scroll", "research", "publication", "diploma", "backpack", "academic"],
     ["thesis", "report"]),
    ("Rocket Huggy.png", "Rocket Huggy",
     "Outlined Huggy with backpack flying inside a white rocket with orange flames.",
     "happy_open_mouth", "tilted_right", "fist_forward",
     ["backpack"], [], [], ["rocket"], ["flames"],
     ["yellow", "white", "blue", "orange"], ["excited", "ambitious"], ["launch", "space"],
     ["rocket", "launch", "fly", "space", "ship", "go", "fast", "startup"],
     ["liftoff", "blastoff"]),
    ("Scan Huggy.png", "Scan Huggy",
     "Outlined Huggy wearing a red laser visor projecting binary code in a red beam.",
     "unknown", "default", "pointing",
     ["laser visor"], [], ["visor"], [], ["binary stream"],
     ["yellow", "red", "black"], ["focused", "tech"], ["scan", "data"],
     ["scan", "laser", "visor", "binary", "data", "vision", "cyclops", "scanner"],
     ["xray", "beam"]),
    ("Violinist Huggy.png", "Violinist Huggy",
     "Outlined Huggy with blue beret playing a brown violin with a baguette as a bow, music notes floating.",
     "peaceful_closed", "default", "holding",
     ["beret"], [], [], ["violin", "baguette bow"], ["music note"],
     ["yellow", "blue", "brown"], ["artistic", "calm"], ["music"],
     ["violin", "violinist", "music", "beret", "baguette", "play", "french", "instrument"],
     ["fiddle", "musician"]),
    ("X-ray Huggy.png", "X-ray Huggy",
     "Outlined Huggy showing a yellow/white split-color body with task, language, and license labels.",
     "winking", "default", "open_palm",
     [], [], [], [], ["labels"],
     ["yellow", "white", "blue"], ["analytical", "happy"], ["metadata", "model-card"],
     ["xray", "x-ray", "metadata", "labels", "task", "language", "license", "card"],
     ["analyze", "inspect"]),
]

# ---------- Huggy Collection 2026 (73) ----------
COLLECTION = [
    # Files that mirror Modern/Outlined
    ("Acedemic Huggy.png", "Acedemic Huggy",
     "Yellow Huggy wearing a graduation cap, smiling and holding a blue pointer stick.",
     "happy_open_mouth", "default", "pointing",
     ["graduation cap"], [], [], ["pointer"], [],
     ["yellow", "purple", "blue"], ["proud", "smart"], ["education", "academic"],
     ["academic", "graduation", "cap", "school", "teacher", "professor", "education"],
     ["scholar", "diploma"]),
    ("breathe deeply.png", "Breathing Huggy",
     "Yellow Huggy with closed eyes and pursed lips, hands raised in dance pose with a music note.",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], ["music note"],
     ["yellow", "purple"], ["calm", "relaxed"], ["meditation"],
     ["breathe", "deeply", "calm", "meditation", "relax", "yoga", "zen", "music"],
     ["mindful", "exhale"]),
    ("computer vision Huggy.png", "computer vision Huggy",
     "Yellow Huggy reading a blue book while holding a pencil and emoji cards.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["book", "pencil", "emoji cards"], [],
     ["yellow", "blue", "red"], ["focused", "happy"], ["ml", "computer-vision"],
     ["vision", "computer-vision", "ml", "ai", "book", "study", "labeling", "annotation"],
     ["cv", "labels"]),
    ("D Huggy.png", "D Huggy",
     "Yellow Huggy as a detective with a magnifying glass, headphones, and a pink eraser.",
     "winking", "default", "holding",
     [], [], ["magnifying glass"], ["magnifying glass", "eraser"], ["question mark"],
     ["yellow", "pink"], ["curious", "investigative"], ["detective"],
     ["detective", "magnifying", "investigate", "spy", "search", "clue", "curious"],
     ["sherlock", "sleuth"]),
    ("dancing.png", "Dancing Huggy",
     "Yellow Huggy with closed eyes whistling a tune, hands raised in playful dance gesture.",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], ["music note"],
     ["yellow", "purple"], ["fun", "happy"], ["dance", "music"],
     ["dancing", "dance", "music", "whistle", "groove", "happy", "rhythm"],
     ["jam", "boogie"]),
    ("dancing-1.png", "Dancing Huggy 2",
     "Yellow Huggy with raised brows and crying-tear face, palms up in a dramatic pose.",
     "crying", "default", "open_palm",
     [], [], [], [], ["tears"],
     ["yellow", "blue"], ["sad", "dramatic"], ["dance", "drama"],
     ["dancing", "dance", "cry", "tears", "drama", "sad", "emotional"],
     ["weep", "expressive"]),
    ("dancing-2.png", "Dancing Huggy 3",
     "Yellow Huggy with crying-tear face giving a thumbs up while waving the other hand.",
     "crying", "default", "thumbs_up",
     [], [], [], [], ["tears", "sparkle"],
     ["yellow", "blue"], ["bittersweet", "dramatic"], ["dance", "drama"],
     ["dancing", "dance", "cry", "tears", "thumbs-up", "drama", "bittersweet"],
     ["weep", "approve"]),
    ("Doodle Huggy.gif", "Doodle Huggy",
     "Hand-drawn doodle style Huggy with messy yellow hair and a music note.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], [], ["music note"],
     ["yellow", "pink"], ["fun", "playful"], ["doodle", "art"],
     ["doodle", "sketch", "drawing", "messy", "music", "fun", "scribble"],
     ["doodled", "handdrawn"]),
    ("Dragon Huggy.png", "Dragon Huggy",
     "Yellow Huggy wearing a green dragon-head costume with antlers and pink scales.",
     "happy_open_mouth", "default", "open_palm",
     ["dragon costume"], [], [], [], [],
     ["yellow", "green", "pink"], ["festive", "playful"], ["lunar-new-year", "mythical"],
     ["dragon", "costume", "lunar", "new-year", "mythical", "antlers", "zodiac"],
     ["chinese-new-year", "wyrm"]),
    ("Frame 6.png", "Boxing Huggy",
     "Yellow Huggy in red and brown boxing helmet rushing forward with hands hugging a video player.",
     "happy_open_mouth", "rushing_left", "holding",
     ["boxing helmet"], [], [], ["video player"], ["motion lines"],
     ["yellow", "red", "brown", "blue"], ["energetic", "happy"], ["sports", "media"],
     ["boxing", "rush", "fast", "video", "play", "media", "energy", "helmet"],
     ["sport", "punch"]),
    ("Frame 9.png", "Rushing Huggy",
     "Yellow Huggy rushing left with one eye winking and a thumbs up gesture.",
     "winking", "rushing_left", "thumbs_up",
     [], [], [], [], ["sparkle"],
     ["yellow"], ["energetic", "happy"], ["motion"],
     ["rush", "run", "fast", "wink", "thumbs-up", "go", "speedy"],
     ["dash", "hurry"]),
    ("Frame 10.png", "Athlete Frowning Huggy",
     "Yellow Huggy in blue wristband rushing left with a small frown and a closed mouth.",
     "sad", "rushing_left", "default",
     [], ["wristband"], [], [], ["motion lines"],
     ["yellow", "blue"], ["determined", "frustrated"], ["sports"],
     ["athlete", "rush", "run", "frown", "sport", "wristband", "tired", "effort"],
     ["jog", "exhausted"]),
    ("Frame 11.png", "Pointing Huggy",
     "Yellow Huggy with one eye winking, smiling, and pointing right with a thumbs up.",
     "winking", "rushing_right", "pointing",
     [], [], [], [], ["sparkle"],
     ["yellow"], ["confident", "happy"], ["direction"],
     ["pointing", "wink", "right", "thumbs-up", "directing", "happy", "confident"],
     ["gesture", "indicate"]),
    ("Frame 92.png", "Sprouting Huggy",
     "Yellow Huggy with a small green sprout growing from its head, looking down at folded hands.",
     "bored", "tilted_down", "default",
     ["sprout"], [], [], [], ["motion lines"],
     ["yellow", "green", "brown"], ["calm", "shy"], ["growth", "nature"],
     ["sprout", "plant", "growing", "head", "nature", "bored", "shy", "leaf"],
     ["seedling", "bud"]),
    ("Frame 93.png", "Gaming Huggy",
     "Yellow Huggy with smug smirk holding a black video game controller in both hands.",
     "smug", "default", "holding",
     [], [], [], ["controller"], [],
     ["yellow", "black"], ["focused", "smug"], ["gaming"],
     ["gaming", "game", "controller", "play", "video-game", "smirk", "console"],
     ["esports", "gamepad"]),
    ("Frame 94.png", "Peeking Huggy",
     "Yellow Huggy peeking out shyly with both hands raised, smiling.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["shy", "happy"], ["greeting"],
     ["peek", "peeking", "shy", "smile", "hello", "hide", "happy"],
     ["peep", "bashful"]),
    ("Frame 97.png", "Tiptoe Huggy",
     "Yellow Huggy tiptoeing left with a tiny smile and pursed mouth, hands clasped.",
     "closed_smile", "tilted_left", "default",
     [], [], [], [], ["motion lines"],
     ["yellow"], ["sneaky", "shy"], ["sneak"],
     ["tiptoe", "sneak", "quiet", "shy", "creep", "stealth", "small"],
     ["sneaky", "stealthy"]),
    ("Frame 98.png", "Athlete Laughing Huggy",
     "Yellow Huggy in blue wristband rushing right, laughing with eyes scrunched closed.",
     "peaceful_closed", "rushing_right", "default",
     [], ["wristband"], [], [], ["motion lines"],
     ["yellow", "blue"], ["happy", "energetic"], ["sports"],
     ["athlete", "rush", "run", "laugh", "sport", "wristband", "happy", "joy"],
     ["jog", "sprint"]),
    ("Game Jam Huggy.png", "Game Jam Huggy",
     "Two yellow Huggies sitting together holding video game controllers, one winking.",
     "winking", "default", "holding",
     [], [], [], ["controller"], ["sparkles"],
     ["yellow"], ["fun", "competitive"], ["gaming"],
     ["game", "gaming", "controller", "jam", "play", "video-game", "console"],
     ["esports", "gamepad"]),
    ("Global Huggy.png", "Global Huggy",
     "Outlined Huggy with starry eyes pointing at a blue globe on a stand.",
     "starry_eyes", "default", "pointing",
     [], [], [], ["globe"], [],
     ["yellow", "blue"], ["excited", "curious"], ["global", "world"],
     ["global", "world", "globe", "earth", "international", "geography", "travel"],
     ["worldwide", "planet"]),
    ("GPU Huggy.png", "GPU Huggy",
     "Outlined Huggy hugging a black GPU chip with a teal core.",
     "starry_eyes", "default", "hugging",
     [], [], [], ["GPU chip"], ["motion lines"],
     ["yellow", "black", "teal"], ["excited", "tech"], ["hardware", "compute"],
     ["gpu", "chip", "compute", "hardware", "graphics", "card", "ml"],
     ["graphics", "processor"]),
    ("Growing model Huggy.png", "Growing model Huggy",
     "Outlined Huggy watering a plant pot growing a blue model crystal.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["watering can"], ["water drops"],
     ["yellow", "blue", "green"], ["nurturing", "happy"], ["model-training", "growth"],
     ["growing", "model", "watering", "plant", "grow", "training", "nurture", "ml"],
     ["cultivate", "develop"]),
    ("Growing model Huggy-2.png", "Growing model Huggy 2",
     "Yellow Huggy with smug smirk holding a thermometer-style ruler with a blue crystal.",
     "smug", "default", "holding",
     [], [], [], ["ruler", "crystal"], [],
     ["yellow", "blue"], ["confident", "knowing"], ["model-training", "guide"],
     ["growing", "model", "guide", "ruler", "crystal", "smug", "training"],
     ["develop", "manual"]),
    ("Growing model Huggy-3.png", "Growing model Huggy 3",
     "Yellow Huggy watering a model crystal sprouting from a plant pot, looking joyful.",
     "happy_open_mouth", "default", "holding",
     [], [], [], ["watering can", "crystal"], ["water drops"],
     ["yellow", "blue", "green"], ["nurturing", "happy"], ["model-training", "growth"],
     ["growing", "model", "watering", "plant", "grow", "training", "nurture"],
     ["cultivate", "develop"]),
    ("Guide Huggy.png", "Guide Huggy",
     "Outlined Huggy with a smug expression holding a large thermometer-ruler with crystal.",
     "smug", "default", "holding",
     [], [], [], ["ruler", "crystal"], [],
     ["yellow", "blue"], ["confident", "knowing"], ["guide", "tutorial"],
     ["guide", "ruler", "tutorial", "howto", "thermometer", "crystal", "smug"],
     ["instruction", "manual"]),
    ("Guide Huggy-1.png", "Guide Huggy 2",
     "Outlined Huggy with magnifying glass eye looking with curiosity, question mark above.",
     "winking", "default", "holding",
     [], [], [], ["magnifying glass"], ["question mark"],
     ["yellow", "pink", "blue"], ["curious", "puzzled"], ["search", "guide"],
     ["guide", "magnifying", "search", "investigate", "question", "wonder"],
     ["inquisitive", "explore"]),
    ("huggy_001__{leaning right}__{hug}__{viking hat and mustache}__{peacefully closed eyes}.png", "Viking Huggy",
     "Yellow Huggy with red braided hair and mustache holding a black-and-white rabbit doll.",
     "peaceful_closed", "leaning_right", "hugging",
     ["red braids", "mustache"], [], [], ["rabbit doll"], [],
     ["yellow", "red", "white"], ["calm", "fierce"], ["nordic", "warrior"],
     ["viking", "horns", "braids", "warrior", "nordic", "peaceful", "hug", "mustache"],
     ["norse", "berserker"]),
    ("huggy_002__{leaning left}__{pointing left}__{headphone}__{open mouth smiling}.png", "DJ Huggy",
     "Yellow Huggy wearing big blue headphones, leaning and pointing with a wide smile.",
     "happy_open_mouth", "leaning_left", "pointing",
     ["headphones"], [], [], [], [],
     ["yellow", "blue"], ["cool", "happy"], ["music"],
     ["dj", "headphones", "music", "point", "lean", "audio", "sound", "song"],
     ["disc-jockey", "beats"]),
    ("huggy_002__{standing straight}__{hug}__{handsome brown horse costume on the head}__{mouth open smiling}.png", "Horse Huggy",
     "Yellow Huggy wearing a brown horse-head costume with flowing black mane.",
     "happy_open_mouth", "default", "open_palm",
     ["horse costume", "black mane"], [], [], [], ["sparkle"],
     ["yellow", "brown", "black"], ["festive", "playful"], ["zodiac", "costume"],
     ["horse", "costume", "mane", "animal", "zodiac", "year", "stallion"],
     ["pony", "equine"]),
    ("huggy_003__{standing 0.75 right}__{greeting}__{dark brown bob haircut}__{facing slightly upward, mouth open smiling}.png", "Bob Huggy",
     "Yellow Huggy with dark brown bob haircut, smiling and waving cheerfully.",
     "happy_open_mouth", "tilted_right", "waving",
     ["brown bob"], [], [], [], ["exclamation"],
     ["yellow", "brown"], ["happy", "friendly"], ["greeting", "hairstyle"],
     ["bob", "haircut", "wave", "hello", "greet", "happy", "fashion"],
     ["bobcut", "fringe"]),
    ("huggy_004__{rushing right}__{running hand}__{blue wrist band}__{comepetitive open mouth smile}.png", "Athlete Huggy",
     "Yellow Huggy wearing a blue wristband rushing right with a competitive open mouth smile.",
     "excited", "rushing_right", "fist_forward",
     [], ["wristband"], [], [], ["motion lines"],
     ["yellow", "blue", "orange"], ["competitive", "energetic"], ["sports"],
     ["athlete", "rush", "run", "wristband", "sport", "race", "compete", "fast"],
     ["jog", "sprint"]),
    ("Huggy Chef.png", "Huggy Chef",
     "Yellow Huggy wearing a tall white chef's hat with a small sugar cube on a tray.",
     "starry_eyes", "default", "open_palm",
     ["chef hat"], [], [], ["sugar cube"], ["sparkles", "hearts"],
     ["yellow", "white"], ["passionate", "happy"], ["cooking", "food"],
     ["chef", "cook", "kitchen", "hat", "food", "baking", "cooking", "sweet"],
     ["baker", "cuisine"]),
    ("Huggy Hi.png", "Huggy Hi",
     "Yellow Huggy with a wide smile and both hands raised in a friendly greeting.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow"], ["friendly", "happy"], ["greeting"],
     ["hi", "hello", "hey", "wave", "greeting", "welcome", "friendly"],
     ["howdy", "salute"]),
    ("Huggy Lab.png", "Huggy Lab",
     "Yellow Huggy in a white lab coat holding up a teal test tube.",
     "happy_open_mouth", "default", "holding",
     [], ["lab coat"], [], ["test tube"], [],
     ["yellow", "white", "teal"], ["curious", "scientific"], ["science"],
     ["lab", "scientist", "test-tube", "science", "chemistry", "research", "experiment"],
     ["chemist", "researcher"]),
    ("Huggy Lab-1.png", "Huggy Lab 2",
     "Yellow Huggy with closed eyes hugging two smaller Huggies tenderly.",
     "peaceful_closed", "default", "hugging",
     [], [], [], ["small huggies"], [],
     ["yellow"], ["loving", "warm"], ["family", "hug"],
     ["lab", "hug", "love", "babies", "small", "family", "warmth", "tender"],
     ["embrace", "cuddle"]),
    ("Huggy Lab-2.png", "Monopoly Huggy",
     "Yellow Huggy with mustache, monocle, and tuxedo, hands raised in a Monopoly-man pose.",
     "smug", "default", "open_palm",
     ["monocle", "mustache"], ["tuxedo"], ["monocle"], [], [],
     ["yellow", "black", "white"], ["wealthy", "smug"], ["business", "rich"],
     ["monopoly", "rich", "tuxedo", "mustache", "monocle", "boss", "ceo", "fancy"],
     ["wealthy", "tycoon"]),
    ("Huggy Lawyer.png", "Huggy Lawyer",
     "Yellow Huggy in black suit holding scales of justice and a white napkin/handkerchief.",
     "happy_open_mouth", "default", "holding",
     [], ["suit"], [], ["scales", "handkerchief"], [],
     ["yellow", "black", "brown"], ["formal", "happy"], ["law", "justice"],
     ["lawyer", "law", "justice", "scales", "court", "attorney", "suit", "legal"],
     ["counsel", "barrister"]),
    ("Huggy Lawyer-1.png", "Judge Huggy",
     "Yellow Huggy in white judicial robe and wig, eyes closed, holding scales of justice.",
     "peaceful_closed", "default", "holding",
     ["judicial wig"], ["robe"], [], ["scales"], [],
     ["yellow", "white", "brown"], ["calm", "wise"], ["law", "justice"],
     ["judge", "law", "justice", "scales", "court", "robe", "wig", "legal"],
     ["magistrate", "verdict"]),
    ("Huggy Lawyer-2.png", "Baguette Violinist Huggy",
     "Yellow Huggy with closed eyes playing a brown violin using a baguette as the bow.",
     "peaceful_closed", "default", "holding",
     [], [], [], ["violin", "baguette bow"], [],
     ["yellow", "brown"], ["artistic", "calm"], ["music", "french"],
     ["violin", "baguette", "music", "french", "play", "instrument", "bread"],
     ["fiddle", "musician"]),
    ("Huggy Medic.png", "Huggy Medic",
     "Yellow Huggy with a white nurse cap and red cross, holding a stethoscope.",
     "happy_open_mouth", "default", "holding",
     ["nurse cap"], [], [], ["stethoscope"], [],
     ["yellow", "white", "red"], ["caring", "happy"], ["medical"],
     ["medic", "nurse", "doctor", "stethoscope", "health", "medical", "hospital"],
     ["physician", "healthcare"]),
    ("Huggy Medic-1.png", "Headphones Huggy",
     "Yellow Huggy wearing big blue over-ear headphones, smiling with palms forward.",
     "happy_open_mouth", "default", "open_palm",
     ["headphones"], [], [], [], [],
     ["yellow", "blue"], ["happy", "musical"], ["music"],
     ["headphones", "music", "audio", "listen", "sound", "song", "happy"],
     ["headset", "beats"]),
    ("Huggy Medic-2.png", "Whistle Huggy",
     "Yellow Huggy with closed eyes whistling a tune while wearing blue headphones.",
     "peaceful_closed", "default", "open_palm",
     ["headphones"], [], [], [], ["music note"],
     ["yellow", "blue", "purple"], ["calm", "musical"], ["music"],
     ["whistle", "headphones", "music", "song", "tune", "calm", "audio"],
     ["humming", "melody"]),
    ("Huggy Medic-3.png", "Starry Eyes Huggy",
     "Yellow Huggy with star-shaped sparkle eyes and a wide open-mouth smile.",
     "starry_eyes", "default", "open_palm",
     [], [], [], [], ["sparkles"],
     ["yellow"], ["excited", "amazed"], ["reaction"],
     ["star", "stars", "starry", "amazed", "wow", "excited", "sparkle", "love"],
     ["dazzled", "wonder"]),
    ("Huggy Medic-4.png", "Smiling Huggy",
     "Yellow Huggy with a happy open-mouth smile and palms raised wide.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["happy"], ["reaction"],
     ["smile", "happy", "joy", "open-mouth", "cheerful", "grin", "laugh"],
     ["glad", "smiley"]),
    ("Huggy Medic-5.png", "Bored Huggy",
     "Yellow Huggy with droopy bored eyes and a flat closed mouth, palms shrugging.",
     "bored", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["bored", "indifferent"], ["reaction"],
     ["bored", "shrug", "meh", "indifferent", "tired", "flat", "uninterested"],
     ["dull", "apathetic"]),
    ("Huggy Medic-7.png", "Frustrated Huggy",
     "Yellow Huggy with bored droopy eyes, clenched mouth, and an angry mark on the head.",
     "angry", "default", "open_palm",
     [], [], [], [], ["anger mark"],
     ["yellow"], ["angry", "frustrated"], ["reaction"],
     ["angry", "frustrated", "mad", "irritated", "bored", "annoyed", "vexed"],
     ["upset", "fury"]),
    ("Huggy Medic-8.png", "Yelling Huggy",
     "Yellow Huggy with sharp angry eyebrows shouting with hands raised in protest.",
     "angry", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["angry", "intense"], ["reaction"],
     ["yell", "shout", "angry", "mad", "scream", "frustrated", "loud"],
     ["rage", "outburst"]),
    ("Huggy Medic-9.png", "Smug Huggy",
     "Yellow Huggy with bored half-closed eyes and a smug closed-mouth expression.",
     "smug", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["smug", "knowing"], ["reaction"],
     ["smug", "smirk", "knowing", "bored", "satisfied", "confident", "cool"],
     ["snarky", "haughty"]),
    ("Huggy Medic-10.png", "Cool Huggy",
     "Yellow Huggy with pixel sunglasses, bow tie, and stylized hair, looking cool.",
     "cool_smirk", "default", "open_palm",
     ["pixel sunglasses", "bow tie", "wavy hair"], [], ["pixel sunglasses"], [], [],
     ["yellow", "black"], ["cool", "smug"], ["meme", "fashion"],
     ["cool", "sunglasses", "shades", "tie", "fancy", "smug", "stylish", "boss"],
     ["dapper", "swag"]),
    ("Huggy Medic-11.png", "Pointing Huggy",
     "Yellow Huggy smiling with one hand pointing to the side and other waving.",
     "happy_open_mouth", "default", "pointing",
     [], [], [], [], [],
     ["yellow"], ["happy", "directing"], ["direction"],
     ["pointing", "direct", "look", "smile", "happy", "indicate", "show"],
     ["gesture", "signal"]),
    ("Huggy Medic-12.png", "Two Thumbs Up Huggy",
     "Yellow Huggy smiling broadly with both thumbs up.",
     "happy_open_mouth", "default", "thumbs_up",
     [], [], [], [], [],
     ["yellow"], ["happy", "approving"], ["reaction"],
     ["thumbs-up", "approve", "good", "yes", "happy", "agree", "great"],
     ["like", "kudos"]),
    ("Huggy Medic-13.png", "Double Thumbs Up Huggy",
     "Yellow Huggy with mouth open in a delighted smile, both hands giving thumbs up.",
     "happy_open_mouth", "default", "thumbs_up",
     [], [], [], [], [],
     ["yellow"], ["happy", "approving"], ["reaction"],
     ["thumbs-up", "approve", "good", "yes", "happy", "great", "double"],
     ["like", "kudos"]),
    ("Huggy Medic-14.png", "Default Huggy",
     "Plain yellow Huggy with mouth open in default smile, palms raised wide.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["happy", "neutral"], ["default"],
     ["default", "smile", "happy", "plain", "basic", "standard", "open"],
     ["base", "standard"]),
    ("Huggy Medic-16.png", "Cowboy Huggy",
     "Yellow Huggy in a brown cowboy hat with a star and blue bandana, smiling.",
     "happy_open_mouth", "default", "open_palm",
     ["cowboy hat"], ["bandana"], [], [], [],
     ["yellow", "brown", "blue"], ["happy", "western"], ["cowboy", "western"],
     ["cowboy", "hat", "western", "sheriff", "bandana", "star", "rancher", "wild-west"],
     ["ranger", "yeehaw"]),
    ("Huggy Medic-17.png", "Wine Huggy",
     "Yellow Huggy with closed eyes drinking from a wine glass, shaka hand gesture.",
     "peaceful_closed", "default", "holding",
     [], [], [], ["wine glass"], [],
     ["yellow", "purple"], ["relaxed", "happy"], ["drink", "social"],
     ["wine", "drink", "glass", "alcohol", "relax", "shaka", "happy", "cheers"],
     ["sip", "merlot"]),
    ("Huggy Okay.png", "Huggy Okay",
     "Yellow Huggy with closed eyes, big smile, and an OK hand gesture.",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["happy", "calm"], ["reaction"],
     ["okay", "ok", "fine", "smile", "happy", "approve", "satisfied"],
     ["alright", "good"]),
    ("Huggy Pop.gif", "Huggy Pop",
     "Animated pop-style Huggy (animated GIF, frame may appear blank).",
     "unknown", "default", "default",
     [], [], [], [], [],
     ["yellow"], ["fun"], ["animated"],
     ["pop", "animated", "gif", "loop", "motion"],
     ["bounce", "wiggle"]),
    ("Huggy Sunny hello.png", "Huggy Sunny hello",
     "Yellow Huggy peeking from edge with a friendly wave on a blue background.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], ["motion lines"],
     ["yellow", "blue"], ["friendly", "happy"], ["greeting", "banner"],
     ["sunny", "hello", "hi", "wave", "greeting", "friendly", "blue"],
     ["howdy", "welcome"]),
    ("Huggy Sunny.png", "Huggy Sunny",
     "Yellow Huggy partially shown smiling on a blue background, hand raised.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow", "blue"], ["happy", "calm"], ["banner"],
     ["sunny", "wave", "happy", "hello", "blue", "background"],
     ["bright", "cheery"]),
    ("Huggy the Pooh meme.png", "Huggy the Pooh meme",
     "Two-panel meme of Huggy: top plain, bottom wearing pixel sunglasses and bow tie.",
     "smug", "default", "open_palm",
     [], [], ["pixel sunglasses", "bow tie"], [], [],
     ["yellow", "gray", "black"], ["smug", "cool"], ["meme"],
     ["meme", "pooh", "sunglasses", "tuxedo", "smug", "cool", "fancy", "comparison"],
     ["bear", "drake"]),
    ("Huggy Yolk.png", "Huggy Yolk",
     "Yellow Huggy hatching out of a cracked white egg shell, smiling.",
     "happy_open_mouth", "default", "open_palm",
     [], [], [], ["egg shell"], [],
     ["yellow", "white"], ["new", "happy"], ["birth"],
     ["yolk", "egg", "hatch", "born", "new", "shell", "baby", "chick"],
     ["hatching", "newborn"]),
    ("Karaoke Huggy.png", "Karaoke Huggy",
     "Yellow Huggy with eyes closed singing into a black microphone with a music note.",
     "peaceful_closed", "default", "holding",
     [], [], [], ["microphone"], ["music note"],
     ["yellow", "blue", "black"], ["happy", "musical"], ["music"],
     ["karaoke", "sing", "microphone", "music", "song", "mic", "performance"],
     ["singing", "vocal"]),
    ("Karaoke Huggy-1.png", "Karaoke Huggy 2",
     "Yellow Huggy winking with a happy open mouth, hand raised.",
     "winking", "default", "waving",
     [], [], [], [], [],
     ["yellow"], ["happy", "playful"], ["reaction"],
     ["wink", "smile", "happy", "playful", "wave", "cute"],
     ["blink", "cheeky"]),
    ("Karaoke Huggy-2.png", "Karaoke Huggy 3",
     "Yellow Huggy with happy open-mouth smile and one hand raised in a friendly wave.",
     "happy_open_mouth", "default", "waving",
     [], [], [], [], [],
     ["yellow"], ["happy", "friendly"], ["greeting"],
     ["wave", "hello", "smile", "happy", "greet", "friendly"],
     ["howdy", "welcome"]),
    ("Karaoke Huggy-3.png", "Cowboy Wizard Huggy",
     "Yellow Huggy in big black wizard/cowboy hat and dark robe giving a thumbs up, sparkle nearby.",
     "closed_smile", "tilted_left", "thumbs_up",
     ["wizard hat"], ["robe"], [], [], ["sparkle"],
     ["yellow", "black"], ["mysterious", "cool"], ["wizard", "cowboy"],
     ["wizard", "cowboy", "hat", "robe", "thumbs-up", "magic", "mysterious", "cool"],
     ["sorcerer", "outlaw"]),
    ("Karaoke Huggy-4.png", "Headphones Wave Huggy",
     "Yellow Huggy wearing blue headphones, smiling with one hand raised in a wave.",
     "happy_open_mouth", "default", "waving",
     ["headphones"], [], [], [], [],
     ["yellow", "blue"], ["happy", "musical"], ["music"],
     ["headphones", "music", "wave", "hello", "audio", "happy", "listen"],
     ["headset", "groove"]),
    ("Karaoke Huggy-5.png", "Star Eyes Wave Huggy",
     "Yellow Huggy with star-shaped sparkle eyes and open-mouth smile, hand raised.",
     "starry_eyes", "default", "waving",
     [], [], [], [], ["sparkles"],
     ["yellow"], ["excited", "amazed"], ["reaction"],
     ["star", "stars", "amazed", "wow", "excited", "wave", "love"],
     ["dazzled", "wonder"]),
    ("Karaoke Huggy-7.png", "Sad Huggy",
     "Yellow Huggy with sad worried eyes and frowning mouth, palms open.",
     "sad", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["sad", "worried"], ["reaction"],
     ["sad", "worried", "frown", "upset", "concerned", "down", "blue"],
     ["sorrow", "unhappy"]),
    ("Snake Huggy.png", "Snake Huggy",
     "Yellow Huggy wearing a green snake hat with big white eyes and red tongue.",
     "happy_open_mouth", "default", "open_palm",
     ["snake hat"], [], [], [], [],
     ["yellow", "green", "red"], ["festive", "playful"], ["lunar-new-year", "zodiac"],
     ["snake", "lunar", "zodiac", "year", "costume", "reptile", "asian"],
     ["serpent", "viper"]),
    ("Super Huggy.png", "Super Huggy",
     "Yellow Huggy in a dynamic flying pose with confetti streaks, fist raised triumphantly.",
     "happy_open_mouth", "rushing_right", "fist_forward",
     [], [], [], [], ["confetti", "speed lines"],
     ["yellow", "red", "blue", "purple"], ["excited", "powerful"], ["super", "celebration"],
     ["super", "hero", "fly", "confetti", "celebrate", "power", "fist", "energy"],
     ["superhero", "victory"]),
    ("Text Generation Wizard Huggy.png", "Text Generation Wizard Huggy",
     "Yellow Huggy in dark wizard hat holding a wooden staff and glowing diamond crystal.",
     "happy_open_mouth", "default", "holding",
     ["wizard hat"], [], [], ["staff", "crystal"], ["floating letters"],
     ["yellow", "blue", "purple"], ["magical", "creative"], ["nlp", "magic"],
     ["wizard", "text", "generation", "magic", "nlp", "staff", "spell", "language"],
     ["mage", "sorcerer"]),
    ("Transformer Agent Huggy.png", "Transformer Agent Huggy",
     "Yellow Huggy with binary-code visor sunglasses holding star-shaped tokens and a star ornament.",
     "cool_smirk", "default", "holding",
     [], [], ["binary visor"], ["star tokens"], [],
     ["yellow", "black", "green"], ["cool", "tech"], ["agents", "ml"],
     ["transformer", "agent", "binary", "code", "ai", "matrix", "visor", "tokens"],
     ["coder", "hacker"]),
    ("Vibing Huggy.gif", "Vibing Huggy",
     "Yellow Huggy with closed eyes and big smile making finger-gun shaka gestures.",
     "peaceful_closed", "default", "open_palm",
     [], [], [], [], [],
     ["yellow"], ["chill", "happy"], ["vibe", "animated"],
     ["vibing", "vibe", "chill", "shaka", "groove", "happy", "animated"],
     ["relax", "mood"]),
]


def make_record(category: str, folder: str, filename: str, display_name: str,
                description: str, expression: str, pose: str, hands: str,
                headwear, outfit, face_acc, held, effects, colors, mood, theme,
                tags, synonyms, used_ids: dict) -> dict:
    base_id = f"{category}__{slugify(display_name)}"
    rec_id = base_id
    n = 2
    while rec_id in used_ids:
        rec_id = f"{base_id}-{n}"
        n += 1
    used_ids[rec_id] = True
    return {
        "id": rec_id,
        "filename": filename,
        "folder": folder,
        "display_name": display_name,
        "category": category,
        "description": description,
        "expression": expression,
        "pose": pose,
        "hands": hands,
        "headwear": headwear,
        "outfit": outfit,
        "face_accessories": face_acc,
        "held_objects": held,
        "effects": effects,
        "colors": colors,
        "mood": mood,
        "theme": theme,
        "tags": tags,
        "synonyms": synonyms,
    }


def main() -> None:
    used = {}
    records = []
    for tup in MODERN:
        records.append(make_record("modern", "modern Huggies", *tup, used_ids=used))
    for tup in OUTLINED:
        records.append(make_record("outlined", "Outlined Huggies", *tup, used_ids=used))
    for tup in COLLECTION:
        records.append(make_record("collection-2026", "Huggy Collection 2026", *tup, used_ids=used))

    # Sanity counts
    counts = {"modern": 0, "outlined": 0, "collection-2026": 0}
    for r in records:
        counts[r["category"]] += 1
    print(f"Counts: {counts}, total {len(records)}")
    assert counts["modern"] == 29, counts
    assert counts["outlined"] == 18, counts
    assert counts["collection-2026"] == 73, counts
    assert len(records) == 120

    OUT.write_text(json.dumps(records, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size:,} bytes, {len(records)} records)")


if __name__ == "__main__":
    main()
